### ISSUE TITLE
L2 regularizer

### ISSUE THREAD

**Issue by vornao** [vornao/neural-network-from-scratch#6]

**Comment by lilf4p** [comment]
`for x, target in zip(data, labels):

                pred = self.__forward_prop__(x)
                deltas = pred - target

                self.__backward_prop__(deltas=deltas, eta=eta)`

Should we change in the online training `deltas = red - target` to be a call to loss and implement different loss methods with regularization and not?
Also I don't understand how Is computed the deltas, is a simple difference, it's not a mse, I know we are just evaluating one example at time, but I thought it should be like (red-target)^2

**Comment by vornao** [comment]
Yes, I left it somehow while debugging. We should add a call to loss derivative: using mse it's 1/2(pred-target) (omitting 1/2 since we're manually tuning hyperparameters). I'll fix it as soon as possible.
